// Root Layout for PhotoBooth App
// Sets up global fonts, metadata, and wraps all pages with consistent HTML structure.

import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Configure Geist Sans and Mono fonts as CSS variables
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// App-wide metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// App-wide viewport settings
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};
// Main layout component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
